# Generated by Django 4.1.5 on 2023-02-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='account_type',
            new_name='related_user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='account_type',
            new_name='related_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_advisor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.AddField(
            model_name='advisor',
            name='advisor_type',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate Advisor'), ('graduate', 'Graduate Advisor')], default='admin', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], default='admin', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('advisor', 'Advisor')], default='admin', max_length=20),
            preserve_default=False,
        ),
    ]
