# Generated by Django 4.1.5 on 2023-03-03 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0002_rename_account_type_advisor_related_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=32)),
                ('catalog_number', models.IntegerField()),
                ('course_description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=64)),
                ('room', models.CharField(max_length=32)),
                ('building_description', models.CharField(max_length=96)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.IntegerField()),
                ('instruction_mode', models.CharField(max_length=32)),
                ('instruction_mode_description', models.CharField(max_length=32)),
                ('units', models.IntegerField()),
                ('term', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.ManyToManyField(to='scheduling_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_identifier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduling_app.courseidentifier')),
                ('instructors', models.ManyToManyField(to='scheduling_app.instructor')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduling_app.meeting')),
                ('registration_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduling_app.registrationinformation')),
            ],
        ),
    ]
