# Generated by Django 4.1.5 on 2023-03-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0003_courseidentifier_instructor_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationinformation',
            old_name='course_number',
            new_name='class_number',
        ),
        migrations.AddField(
            model_name='meeting',
            name='days',
            field=models.CharField(default='MoWe', max_length=32),
            preserve_default=False,
        ),
    ]
