# Generated by Django 4.1.5 on 2023-03-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0004_rename_course_number_registrationinformation_class_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='meeting',
        ),
        migrations.AddField(
            model_name='course',
            name='meeting',
            field=models.ManyToManyField(to='scheduling_app.meeting'),
        ),
    ]
