# Generated by Django 4.1.5 on 2023-03-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0005_remove_course_meeting_course_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waitlist_number', models.IntegerField()),
                ('waitlist_capacity', models.IntegerField()),
                ('class_capacity', models.IntegerField()),
                ('enrollment_number', models.IntegerField()),
                ('enrollment_capacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='registrationinformation',
            name='component',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
