# Generated by Django 4.1.5 on 2023-03-07 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0006_enrollmentinformation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_information',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='scheduling_app.enrollmentinformation'),
            preserve_default=False,
        ),
    ]
