# Generated by Django 4.1.5 on 2023-03-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0007_course_enrollment_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationinformation',
            name='units',
            field=models.CharField(max_length=16),
        ),
    ]
