# Generated by Django 4.1.7 on 2023-04-02 20:26

from django.db import migrations, models
import scheduling_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0011_remove_studentschedule_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentschedule',
            name='status',
            field=models.CharField(choices=[(scheduling_app.models.StudentSchedule.Status['NOT_SUBMITTED'], 'Not Submitted'), (scheduling_app.models.StudentSchedule.Status['PENDING'], 'Pending'), (scheduling_app.models.StudentSchedule.Status['APPROVED'], 'Approved'), (scheduling_app.models.StudentSchedule.Status['REJECTED'], 'Rejected')], max_length=16),
        ),
    ]
