# Generated by Django 4.1.7 on 2023-04-14 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0013_alter_studentschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling_app.courseidentifier'),
        ),
    ]
