# Generated by Django 4.1.7 on 2023-04-26 23:04

from django.db import migrations, models
import scheduling_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0014_alter_course_course_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentschedule',
            name='status',
            field=models.CharField(choices=[(scheduling_app.models.StudentSchedule.Status['NOT_SUBMITTED'], 'Not Submitted'), (scheduling_app.models.StudentSchedule.Status['PENDING'], 'Pending'), (scheduling_app.models.StudentSchedule.Status['APPROVED'], 'Approved'), (scheduling_app.models.StudentSchedule.Status['REJECTED'], 'Rejected')], default='Status.NOT_SUBMITTED', max_length=32),
        ),
    ]
